version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: escape-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api

  api:
    build: ./api
    container_name: escape-api
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount .pem securely (read-only)
      - ./dockersequelizekey.pem:/run/secrets/dockersequelizekey.pem:ro
